#!/usr/bin/env python3
"""Create a tiny synthetic SPEAR dataset for smoke tests and tutorials."""

from __future__ import annotations

import argparse
from pathlib import Path

import anndata as ad
import numpy as np
import pandas as pd
import scipy.sparse as sp


def _write_gtf(path: Path, gene_names: list[str], starts: list[int]) -> None:
    rows = []
    for idx, (gene_name, start) in enumerate(zip(gene_names, starts), start=1):
        end = start + 1000
        strand = "+" if idx % 2 else "-"
        attrs = f'gene_id "{gene_name}"; gene_name "{gene_name}";'
        rows.append(f"chr1\tspear\tgene\t{start}\t{end}\t.\t{strand}\t.\t{attrs}\n")
    path.write_text("".join(rows))


def create_tiny_example(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    rng = np.random.default_rng(42)
    n_cells = 48
    gene_names = [f"Gene{i}" for i in range(1, 7)]
    gene_starts = [20_000 + i * 15_000 for i in range(len(gene_names))]

    peak_rows = []
    peak_names = []
    for gene_idx, start in enumerate(gene_starts):
        tss = start if (gene_idx + 1) % 2 else start + 1000
        for offset in (-1500, -500, 500, 1500):
            peak_start = tss + offset
            peak_end = peak_start + 250
            peak_names.append(f"chr1:{peak_start}-{peak_end}")
            peak_rows.append({"chrom": "chr1", "start": peak_start, "end": peak_end})

    n_peaks = len(peak_rows)
    latent = rng.normal(size=(n_cells, 2))
    peak_weights = rng.uniform(0.2, 1.0, size=(2, n_peaks))
    atac_dense = rng.poisson(np.exp(latent @ peak_weights * 0.15)).astype(np.float32)
    dropout = rng.random(size=atac_dense.shape) < 0.35
    atac_dense[dropout] = 0.0

    rna_dense = np.zeros((n_cells, len(gene_names)), dtype=np.float32)
    for gene_idx in range(len(gene_names)):
        cols = slice(gene_idx * 4, gene_idx * 4 + 4)
        local_signal = atac_dense[:, cols].sum(axis=1)
        noise = rng.normal(scale=0.4, size=n_cells)
        rna_dense[:, gene_idx] = np.clip(local_signal * 0.8 + noise + 1.0, 0.0, None)

    cell_names = [f"tiny_cell_{i:03d}" for i in range(n_cells)]
    obs = pd.DataFrame(
        {
            "sample": [f"tiny_rep{(i % 4) + 1}" for i in range(n_cells)],
            "condition": ["synthetic"] * n_cells,
        },
        index=cell_names,
    )

    atac = ad.AnnData(
        X=sp.csr_matrix(atac_dense),
        obs=obs.copy(),
        var=pd.DataFrame(peak_rows, index=peak_names),
    )
    rna = ad.AnnData(
        X=rna_dense,
        obs=obs.copy(),
        var=pd.DataFrame(index=gene_names),
    )
    rna.layers["log1p_cpm"] = np.log1p(rna_dense)

    atac.write_h5ad(output_dir / "tiny_ATAC.h5ad")
    rna.write_h5ad(output_dir / "tiny_RNA.h5ad")
    _write_gtf(output_dir / "tiny.gtf", gene_names, gene_starts)

    pd.DataFrame({"gene_name": gene_names}).to_csv(
        output_dir / "tiny_genes.csv", index=False
    )
    (output_dir / "README.md").write_text(
        "Tiny synthetic SPEAR example data generated by "
        "`python scripts/create_tiny_example_data.py`.\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/examples/tiny"),
        help="Directory where tiny_ATAC.h5ad, tiny_RNA.h5ad, tiny.gtf, and tiny_genes.csv are written.",
    )
    args = parser.parse_args()
    create_tiny_example(args.output_dir)
    print(f"Wrote tiny SPEAR example data to {args.output_dir}")


if __name__ == "__main__":
    main()
